version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ../src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped

  # Ajoutez d'autres services si nécessaire (base de données, cache, etc.)

volumes:
  node_modules:
